### ISSUE TITLE
[Agent] Invalid URI path in the Swagger

### ISSUE THREAD

**Issue by powerkimhub** [cloud-barista/cm-honeybee#14]
- swagger path 점검 필요합니다.
- agent 가동 후 swagger에서 다음처럼 시도하면, `Not Found` 발생합니다. 
  - ![image](https://github.com/cloud-barista/cm-honeybee/assets/46367962/e96f3c06-76b2-41c2-bdca-f1b96869d90f)

- 다음처럼, path에 `honeybee-agent` 추가하면 잘 동작합니다. (software도 동일)

curl -X 'GET'   'http://xxx.xxx.xxx.xxx:8082/honeybee-agent/infra'   -H 'accept: application/json'

```json
{
 "compute": {
  "os": {
   "os": {
    "name": "linux",
    "vendor": "ubuntu",
    "version": "22.04.2 LTS (Jammy Jellyfish)",
    "release": "22.04",
    "architecture": "x86_64"
   },
   "kernel": {
    "release": "5.15.0-112-generic",
    "version": "#122-Ubuntu SMP Thu May 23 07:48:21 UTC 2024",
    "architecture": "x86_64"
   },
   "node": {
    "hostname": "powerkim-dev",
    "hypervisor": "kvm",
    "machineid": "004860cb-990e-46f1-9237-3e3a2cbad236",
    "timezone": "KST"
   }
  ... 중략 ...
```

**Comment by ish-hcc** [comment]
@powerkimhub 확인해서 수정하도록 하겠습니다 현황 확인해 주셔서 감사합니다!
