### ISSUE TITLE
[Guide] Quick Usage Guide Desired

### ISSUE THREAD

**Issue by powerkimhub** [cloud-barista/cm-honeybee#19]
- 제공해주신 Readme와 swagger를 참고하여, 간단히 활용해보았습니다. 
- 현재, Readme와  swagger로도 어느 정도 충분할수도 있지만,
- 처음 사용자를 위해서 활용 순서를 Readme 뒷 부분 등에 
  - 간략히 공유해주시면 더 빠르고 편하게 사용할 수 있었을 것 같습니다. 
- 활용 과정에서 절차를 아래와 같이 간략히 정리해 보았습니다.
- 참고해주시기 바랍니다.  

### [활용 순서]
1. 에이전트/서버 실행
2. 소스그룹 생성
3. 연결설정 등록
4. 소스정보 저장(그룹ID, 연결ID)
5. 소스정보 활용(그룹ID, 연결ID)

---

**1. 에이전트/서버 실행**
  - readme 참고

**2. 소스그룹 생성** => groupid 획득
  - swagger 참고
  - ex) curl -X 'POST' \
  'http://172.24.190.123:8081/honeybee/source_group' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "description": "string",
  "name": "powerkim"
}'

**3. 연결설정 등록** => sgId 획득
  - swagger 참고
  - ex) curl -X 'POST' \
  'http://172.24.190.123:8081/honeybee/source_group/b9e86d53-9fbe-4a96-9e06-627f77fdd6b7/connection_info' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "description": "string",
  "ip_address": "xxx.xxx.xxx.xxx",
  "name": "powerkim",
  "password": "string",
  "private_key": "-----BEGIN RSA PRIVATE KEY-----\n******\n-----END RSA PRIVATE KEY-----",
  "ssh_port": 22,
  "user": "ubuntu"
}
'

**4. 소스정보 저장(Import Source Info)** => Server에 Source Info 저장
  - swagger 참고 (확인필요: https://github.com/cloud-barista/cm-honeybee/issues/17)
  - ex) curl -X 'GET' \
  'http://172.24.190.123:8081/honeybee/source_group/b9e86d53-9fbe-4a96-9e06-627f77fdd6b7/connection_info/2f678139-e6e6-43e8-9722-33b834efc563/import/infra' \
  -H 'accept: application/json'

**5. 소스정보 활용(Get Soource Info)** => Server로부터 수집된 Source Info 획득
  - swagger 참고
  - ex) curl -X 'GET' \
  'http://172.24.190.123:8081/honeybee/source_group/b9e86d53-9fbe-4a96-9e06-627f77fdd6b7/connection_info/2f678139-e6e6-43e8-9722-33b834efc563/infra' \
  -H 'accept: application/json'

※ 다음 이슈 적용 여부 확인 필요: https://github.com/cloud-barista/cm-honeybee/issues/18

**Comment by ish-hcc** [comment]
@powerkimhub 
말씀해 주신대로 README 반영하였습니다.
테스트 해주셔서 감사합니다.

Fixed by: https://github.com/cloud-barista/cm-honeybee/commit/66e8817ddbb9db1d144309986bc8778a205a0de8
