### ISSUE TITLE
Questions about the use of always-on servers

### ISSUE THREAD

**Issue by yunkon-kim** [cloud-barista/cm-honeybee#24]
기존에 지원해주신 상시 구동 서버와 관련하여 문의 드립니다.

최근 개선된 사항들이 반영되어 활용 방법이 달라진 것으로 파악됩니다. 

우선, README에 있는 사항들을 바탕으로 아래와 같이 시도 해보았습니다만, 소스 인프라 형상 정보를 얻을 수 없었습니다. 

아마도 NamdID 관련된 사항으로 보이는데요. 관련하여 API 샘플 또는 Default sgId를 제공해 주실 수 있을까요?

(README 참고 부분)
- [Honeybee Server APIs (Swagger Document)](https://cloud-barista.github.io/cb-tumblebug-api-web/?url=https://raw.githubusercontent.com/cloud-barista/cm-honeybee/main/server/pkg/api/rest/docs/swagger.yaml)
- [6. Get saved source information.](https://github.com/cloud-barista/cm-honeybee?tab=readme-ov-file#6-get-saved-source-information)

참고 - Endpoint는 http://xxx.xxx.xxx.224:8081를 활용하였습니다.

(시도한 사항)
1. source_group 조회

- 요청: GET `/honeybee/source_group`

- 응답:
```
[
 {
  "id": "692b8f81-f7cf-4ffd-b174-89dfb09f487c",
  "name": "migration group test",
  "description": "test group"
 },
 {
  "id": "7273983a-308b-43a2-b8c3-5821b66bc9f6",
  "name": "test sourcegroup create",
  "description": "test description"
 },
 {
  "id": "fcfa9ba7-3429-498e-8612-5539a691bc81",
  "name": "sourcegroup01",
  "description": "ss 01"
 }
]
```

2. 인프라 형상 정보 조회

1 번에서 얻은 3 가지 id로 시도해 봤을 때, 같은 결과를 리턴하고 있습니다.

- 요청: `GET /honeybee/source_group/{sgId}/infra`
- 응답: 
```
{"message":"Not Found"}
```

(추가 확인 사항)

추가로, 3 가지 name(공백은 - 로 대체)으로 시도해 봤을 떄의 결과가 다음과 같습니다.

- 요청: `GET /honeybee/source_group/{sgId}/infra`
- 응답: 
```
{ "error": "SourceGroup not found with the provided ID"}
```

**Comment by ish-hcc** [comment]
@yunkon-kim 현재 아직 소스 작업만 하고 실제 서버에는 업데이트 된 바이너리가 적용이 안되어 있습니다.
업데이트하여 테스트 후 현황 공유 드리도록 하겠습니다!

**Comment by yunkon-kim** [comment]
@ish-hcc 넵 감사합니다 :-)

**Comment by powerkimhub** [comment]
cf) https://github.com/cloud-barista/cm-honeybee/issues/18

**Comment by yunkon-kim** [comment]
@ish-hcc @powerkimhub 
혹시 몰라서, name으로 테스트해보았습니다. 결과를 위에 추가해 놓았습니다.

**Comment by ish-hcc** [comment]
No more related since CI/CD is working properly.
