### ISSUE TITLE
Need to add an API that return/response on-premise model

### ISSUE THREAD

**Issue by yunkon-kim** [cloud-barista/cm-honeybee#35]
@ish-hcc (cc. @powerkimhub)

안녕하세요. Honeybee API 추가를 부탁 드립니다. 

지금까지의 여건 상, Honeybee에서는 소스 컴퓨팅 인프라에 대한 형상 정보를 그대로 제공(Raw 데이터)하는 API가 제공되었습니다.

**On-premise 모델 (a.k.a. 인프라 소스 모델) 초안을 공유드리오니, 형상 정보를 정제(Refine) 및 제공하는 API 추가를 부탁드립니다.**
: 기존 제공되던 형상 정보를 On-premise 모델에 담아서 리턴해주시는 정도의 API이면 될 것 같습니다.
: Honeybee에서 공유해주신 형상 정보 및 기존 자료들을 바탕으로,
: 마이그레이션에 필요한 것으로 보이는 정보들만으로 정제 및 모델화한 버전입니다. (Depth도 가급적 줄여준 상태입니다.)

: 관련 모델 pkg
```go
import onprem "github.com/cloud-barista/cm-model/infra/onprem"
```

: On-premise model과 관련한 이슈, 개선의견 등이 있으시면 편하게 말씀해주시기 바랍니다 ^^

(요약)
: on-premise 모델을 별도 저장소 cm-model에서 제공해 봤습니다. 
: 실험적이고, 모델만 import 하고 싶은데, 관련 없는 pkg들이 영향을 주는 것을 피하고자 별도의 저장소를 개설하였습니다.
: 자세한 사항은 https://github.com/cloud-barista/cm-model 를 참고하시기 바랍니다.

**Comment by yunkon-kim** [comment]
단위와 관련하여 말씀드릴 사항이 있습니다. 

전체적으로 봤을 때, 단위를 GiB, GHz로 통일하면 좋을 것 같았습니다. 이를 주석에 남겨 놓았으니 검토 부탁 드리겠습니다.
https://github.com/cloud-barista/cm-model/blob/main/infra/onprem/infra.go

**Comment by yunkon-kim** [comment]
@ish-hcc 마이너한 수정 사항이 있었습니다 🙏  참고 부탁드립니다.

**Comment by ish-hcc** [comment]
@yunkon-kim 확인했습니다 수고하셨습니다! 확인해서 작업해보도록 하겠습니다

**Comment by ish-hcc** [comment]
@yunkon-kim 
박사님 안녕하세요? 작업해주신 cm-model을 활용해서 honeybee에서 정제된 데이터를 반환해 주는 API를 구현하여 테스트 완료 하였습니다.
한가지 제안 드릴 사항이 있는데, Gateway의 경우 Array 형태로 인터페이스 마다 존재 할 수 있도록 하고,
IP의 경우에도 Array 형태로, 여러 IP를 담을 수 있도록 개선해 주시면 어떨까 합니다.
현재 Honeybee Agent에서는 인터페이스 마다 다중 Gateway, 다중 IP를 수집하고 있습니다.

실제 인프라 구성에서도 참고가 되지 않을까 하여 제안드립니다.
아니면, 인프라 추천, 마이그레이션에서만 현 상태를 유지하고, 필요에 의해서 다중 Gateway, 다중 IP를 봐야 할때는
정제된 데이터가 아닌 수집된 Raw데이터를 참고한다고 하면, 현 상태를 유지해도 될 것 같습니다.

**Comment by yunkon-kim** [comment]
@ish-hcc 의견 공유 감사합니다 :-)

의견 주신 모델 관련 사항 논의를 위해 https://github.com/cloud-barista/cm-model/issues/5 를 열었습니다.

**Comment by yunkon-kim** [comment]
cm-model v0.0.2 release 하였습니다. 참고하시기 바랍니다 :-)

https://github.com/cloud-barista/cm-model/releases/tag/v0.0.2

**Comment by yunkon-kim** [comment]
@ish-hcc 

CM-Honeybee 및 CM-Beetle에 cm-model v0.0.2를 적용 후에, CM-Beetle에서 테스트를 진행할 예정입니다. 

아마도, CM-Beetle 테스트를 통과하면, CM-Butterfly, CM-Cicada 등에서 통합 및 테스트를 진행하시는데 큰 이슈는 없을 것으로 예상하고 있습니다. 

관련하여 CM-Honeybee의 API 제공 일정과 관련하여 문의 드립니다. 여러가지 사안으로 바쁘실테니 대략적인 일정만 공유해주시면 될 것 같습니다 :-)

(참고) cm-model v0.0.2에 이슈가 있을 시 추가 업데이트 진행하겠습니다.

**Comment by ish-hcc** [comment]
@yunkon-kim 
v0.0.2 업데이트 해주셔서 감사합니다
honeybee agent, server 작업 완료 후 정제된 데이터 제공 되도록 업데이트 하였습니다

### Honeybee Agent, Server 사용 Simple Guide
https://github.com/cloud-barista/cm-honeybee/blob/main/README.md

### Server에서 정제된 데이터를 제공하는 API
https://cloud-barista.github.io/cb-tumblebug-api-web/?url=https://raw.githubusercontent.com/cloud-barista/cm-honeybee/main/agent/pkg/api/rest/docs/swagger.yaml#/%5BInfra%5D%20Get%20infra%20info/get-infra-info

**Comment by yunkon-kim** [comment]
@ish-hcc 바쁘실텐데 빠르게 작업해주셔서 감사합니다!

간단히 확인해주실 부분이 있어보입니다 ^^;;

정제된 데이터를 제공하는 API는 다음 링크의 둘 중 하나로 예상하는데요.
https://cloud-barista.github.io/cb-tumblebug-api-web/?url=https://raw.githubusercontent.com/cloud-barista/cm-honeybee/main/server/pkg/api/rest/docs/swagger.yaml#/%5BGet%5D%20Get%20refined%20source%20info

API docs 상에서 Refined data를 제공하는 API와 Raw data를 제공하는 API의 responses가 동일하게 나타나는 것으로 보여서 확인을 부탁드립니다.

**Comment by ish-hcc** [comment]
@yunkon-kim 
아 제가 실수로 swagger 모델을 cm-model 로 지정하지 않았네요 확인하여 업데이트 하였습니다! 감사합니다.

**Comment by yunkon-kim** [comment]
@ish-hcc 넵! 감사합니다 :-)

**Comment by yunkon-kim** [comment]
@ish-hcc 

API docs 를 통해 두 API가 다음과 같이 구분되는 것으로 파악하였습니다. 두 번째 API를 활용하여 Beetle에서 테스트 진행하겠습니다.

1. `GET /source_group/{sgId}/connection_info/{connId}/infra/refined` :소스 컴퓨팅 인프라에 포함된 Server 1대의 정보
2. `GET /source_group/{sgId}/infra/refined` : 소스 컴퓨팅 인프라의 정보

**Comment by ish-hcc** [comment]
@yunkon-kim 네 맞습니다 감사합니다.
