### ISSUE TITLE
Share several issues on connection_info registration API

### ISSUE THREAD

**Issue by yunkon-kim** [cloud-barista/cm-honeybee#36]
API : `POST /source_group/{sgId}/connection_info`

AWS의 VM을 등록하기 위해 시도하던 중, 다음 두 가지 이슈가 있어 공유드립니다.

이슈 1.
PrivateKey를 2가지 형태로 입력해봤고, 모두 다음 오류를 리턴하였습니다.  (형태 1 \n 포함, 형태 2 \n 미포함)
: key format 관련 이슈 인지, 길이 체크 구분의 이슈인지 확인이  필요할 것 같습니다.
{
  "error": "error occurred while encrypting the private key (crypto/rsa: message too long for RSA key size)"
}

이슈 2. 위와 같이 실패 한 이후, 동일한 name에 PrivateKey만 수정했을 때, 다음 오류를 리턴하고 있습니다. 
: 실패 시, metadata가 삭제되지 않은 것 같습니다.
{
  "error": "constraint failed: UNIQUE constraint failed: connection_infos.name (2067)"
}

(사소한 이슈)
VM에 접속하려다 보니 username과 sshkey를 등록하면되는데요. Password가 required로 되어있어, 아무 값이나 입력해야하는 상황이 있었습니다.

**Comment by ish-hcc** [comment]
@yunkon-kim 
테스트 하면서 확인 못한 부분이 존재 했네요 확인해 주셔서 감사합니다.

1. 말씀해 주신 부분이 private key, password 노출 방지를 위해 암호화 하도록 구성하였는데 기본으로 설정 된 키 값이 private key 암호화에 영향이 있는 것으로 추측되네요. 해당 부분 확인해 보도록 하겠습니다.

2. 말씀해 주신 부분 데이터 관련해서 확인해 보도록 하겠습니다. 감사합니다.

사소한 이슈.
agent 설치를 위해 sudo 권한이 필요하여서 그렇게 하였었는데요
ssh-key로 접속해서 사용하는 경우를 고려해서 해당 부분 수정하도록 하겠습니다

**Comment by ish-hcc** [comment]
Issue has been resolved. :)
