### ISSUE TITLE
Failed to run linter when executing the `make` command

### ISSUE THREAD

**Issue by yunkon-kim** [cloud-barista/cm-honeybee#5]
서버 실행 시 아래와 같은 증상이 발생하여 공유차 이슈를 오픈하였습니다.

`make` 실행 시 Running linter 상에 이슈가 있는 것 같습니다.
```bash
Checking dependencies...
Running linter...
make: *** [Makefile:22: lint] Killed
```

다음와 같이 `golangci-lint`의 별도 설치 후 `make` 수행하였을 때에도 증상이 같았습니다.
```bash
go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
```

**Comment by ish-hcc** [comment]
lint설정을 다시 한번 확인해보고, 문제가 될 경우 그냥 빌드만 수행할때는 lint 체크를 안하도록 해야할것 같습니다.
확인해주셔서 감사합니다.

**Comment by ish-hcc** [comment]
Fixed by https://github.com/cloud-barista/cm-honeybee/commit/7754043e3ad2e7a9046f27d8f1a52e22a1a9a4fc
