### ISSUE TITLE
no SMBIOS entry point not found in memory

### ISSUE THREAD

**Issue by yunkon-kim** [cloud-barista/cm-honeybee#6]
소스 컴퓨팅 인프라 형상 정보를 추출하기 위해 CM-Honeybee를 구동해보는 과정에서 다음과 같은 이슈가 발생하였습니다.

지난번에 현황을 공유해 주신 부분인것 같은데요. 확실하지 않아 재차 문의를 드립니다.

아래 사항에 대해 "BIOS 세팅" 에서 "다른 라이브러리로 대체" 하실 계획이신지요?
(맞다면 대략적인 활용 가능시기를 함께 알려주시면 좋을 것 같습니다.)

---
참고차 실행 및 분석 내용을 공유 드립니다.

**요청 API**
- Call  `GET /infra` API

**응답** 
```json
{
  "error": "Internal error occurred. (Reason: Failed to get information of the infra., Error: failed to open stream: no SMBIOS entry point found in memory)"
}
```

**`/driver/conpute_linux.go` line 82 ~ 86 과 연관된 것으로 파악**
```go
	// Get DMI
	dmi, err := dmidecode.New()
	if err != nil {
		return compute, err
	}
```

**관련하여 간단히 파악해본 해결 방법(확실하진 않습니다 ^^;;)**
1. BIOS/UEIF 설정 변경
2. `lshw`, `lscpu`, `lsblk` 패키지 활용

**Comment by ish-hcc** [comment]
확인해 주셔서 감사합니다.
테스트 환경의 시스템 사양과 BIOS가 CMS 또는 Legacy/UEFI 중 어떻게 동작하고 있는지 등을 알 수 있을까요?
(+추가로 Google 검색중 관련이 있나 싶은 부분이 있어 추가로 Memory 종류가 어떤건지 확인 부탁드립니다.)
제가 테스트한 환경들은 아래와 같은데 증상이 재현되지 않아서 문의드립니다.

- Legacy BIOS로 동작중인 Ubuntu 22.04가 설치된 사내 서버 (Memory: DDR4)
- UEFI로 동작중인 Ubuntu 23.10 업무 데스크탑 (Memory: DDR4)
- UEFI로 동작중인 Windows 11 노트북 (Memory: DDR4)
- Legacy BIOS로 동작중인 QEMU KVM기반 Linux 환경들 (Host Memory: DDR4)
- UEFI로 동작중인 VMWare VM (Host Memory: DDR4)

**Comment by ish-hcc** [comment]
@yunkon-kim
추가로 이전에 말씀드렸던 이슈사항은 NVIDIA 그래픽 카드 정보 수집을 할때 NVIDIA에서 제공하는 Go 라이브러리가 있는데 해당 라이브러리가 CGO를 사용하면서, Go에서 Static 빌드시 CGO_ENABLED=0 환경변수 설정으로 인해 Static 빌드가 되지 않는 문제가 있었습니다.
따라서 실행하는 운영체제 환경의 libc 버전에 따라 빌드된 바이너리가 실행이 안되는 문제가 있었습니다.

이부분은 Linux 환경에서 NVIDIA 그래픽 드라이버 설치시 제공되는 nvidia-smi 명령어를 활용하여 정보수집이 가능하여 해결된 부분입니다.
감사합니다.

**Comment by yunkon-kim** [comment]
@ish-hcc 다양한 환경에서 테스트해 주시고, 상세히 설명해주셔서 감사드립니다!

아무래도 제 개발환경이 독특한것 같습니다^^;;

먼저 환경을 말씀드리면 Windows10 WSL2 Ubuntu 22.04에서 cm-honeybee 서버를 실행한 상황입니다.

UEFI/BIOS 및 메모리에 대해서는 다음주 월요일에 확인하는대로 공유 드려야 할 것 같습니다. 일정 참고 부탁드립니다.

**Comment by yunkon-kim** [comment]
@ish-hcc 안녕하세요. 아래와 같이 BIOS 모드와 Memory 정보를 말씀드립니다 :-)
- BIOS 모드: UEFI
- Memory는: SK hynix 8GB 1rx8 PC4 2666v-ua2-11

아무래도 CM-Honeybee에 API 요청하여 소스 컴퓨팅 형상 정보를 얻을 수 있기 전까지, 다른 환경에서 CM-Honeybee를 구동 및 활용하는 것이 좋겠죠? ^^;;

**Comment by yunkon-kim** [comment]
@ish-hcc 오프라인 회의에서 해당 항목은 Out-of-scope로 논의되었기에 close 하도록 하겠습니다. 

WSL2을 마이그레이션 하는 실 사례가 발생시 재 오픈하면 될 것 같습니다.

이후, 실행 및 구동과 관련한 가이드 문서 업데이트하실때 "참고 - WSL2 미지원" 정도의 메모를 남겨주시면 좋을 것 같습니다.

**Comment by ish-hcc** [comment]
@yunkon-kim 네 참고하도록 하겠습니다. 확인해주셔서 감사합니다!
